"""event_id as unique

Revision ID: 59d03fdb7c38
Revises: bd706efb78ca
Create Date: 2025-10-01 11:33:10.834384

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59d03fdb7c38'
down_revision = 'bd706efb78ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'features', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='unique')
    # ### end Alembic commands ###