"""add table features

Revision ID: 5a89352b9e79
Revises: abc8052901ac
Create Date: 2025-09-30 01:54:50.702415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a89352b9e79'
down_revision = 'abc8052901ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('mag', sa.DECIMAL(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('tz', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('felt', sa.Integer(), nullable=True),
    sa.Column('cdi', sa.DECIMAL(), nullable=True),
    sa.Column('mmi', sa.DECIMAL(), nullable=True),
    sa.Column('alert', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tsunami', sa.Integer(), nullable=True),
    sa.Column('sig', sa.Integer(), nullable=True),
    sa.Column('net', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('ids', sa.String(), nullable=True),
    sa.Column('sources', sa.String(), nullable=True),
    sa.Column('types', sa.String(), nullable=True),
    sa.Column('nst', sa.Integer(), nullable=True),
    sa.Column('dmin', sa.DECIMAL(), nullable=True),
    sa.Column('rms', sa.DECIMAL(), nullable=True),
    sa.Column('gap', sa.DECIMAL(), nullable=True),
    sa.Column('mag_type', sa.String(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(), nullable=True),
    sa.Column('longitude', sa.DECIMAL(), nullable=True),
    sa.Column('depth', sa.DECIMAL(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('metadata_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadatas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=True)
    op.drop_index(op.f('ix_metadata_id'), table_name='metadatas')
    op.create_index(op.f('ix_metadatas_id'), 'metadatas', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadatas_id'), table_name='metadatas')
    op.create_index(op.f('ix_metadata_id'), 'metadatas', ['id'], unique=True)
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###