"""add execution_logs

Revision ID: 5fb7e63806a6
Revises: 5a89352b9e79
Create Date: 2025-09-30 19:13:26.722216

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5fb7e63806a6'
down_revision = '5a89352b9e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_name', sa.String(), nullable=False, comment='Name of the endpoint being called.'),
    sa.Column('execution_time', sa.Double(), nullable=False, comment='Execution time in seconds.'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='Status code returned.'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='Parameters sent to the endpoint.'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation time of the execution.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    # ### end Alembic commands ###