"""metadata_id in execution_logs

Revision ID: bd706efb78ca
Revises: 5fb7e63806a6
Create Date: 2025-09-30 19:39:36.425253

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bd706efb78ca'
down_revision = '5fb7e63806a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_logs', sa.Column('metadata_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'execution_logs', 'metadatas', ['metadata_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'execution_logs', type_='foreignkey')
    op.drop_column('execution_logs', 'metadata_id')
    # ### end Alembic commands ###