"""nullable metadata_id in execution_logs

Revision ID: f9a15b4bd25c
Revises: 59d03fdb7c38
Create Date: 2025-10-01 15:52:09.588520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f9a15b4bd25c'
down_revision = '59d03fdb7c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_logs', 'metadata_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_logs', 'metadata_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###